### ISSUE TITLE
New error 

### ISSUE THREAD

**Issue by RikkaTotsuka** [rhenwinch/Auto-SMMO#2]
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:5260)
	at f7.a.b(Unknown Source:15)
	at j7.f.c(SourceFile:521)
	at j7.f$b.l(Unknown Source:12)
	at j8.a.r(Unknown Source:8)
	at a9.m0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

Error occurs when taking steps

**Comment by RikkaTotsuka** [comment]
Another one that appeared

com.google.gson.i: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(Unknown Source:69)
	at com.google.gson.Gson.c(SourceFile:35)
	at com.google.gson.Gson.b(SourceFile:1)
	at j7.j.d(SourceFile:487)
	at j7.j$f.l(Unknown Source:12)
	at j8.a.r(Unknown Source:8)
	at a9.m0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at d7.a.b(Unknown Source:50)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(Unknown Source:19)
	... 14 more
